(defun my-marker-test ()
  (interactive)
  (let (end)
    (goto-char (point-min))
    (save-excursion
      (search-forward "--end")
      (goto-char (match-beginning 0))
      (setq end (point-marker))
      (message "end is %d" (point))
      (sit-for 3))
    (while (< (point) end)
      (insert "Test!!")
      (forward-line 1))
    (goto-char end)))